service: import-service

frameworkVersion: "3"

plugins:
  - serverless-webpack

custom:
  accountId: 449436809015
  bucketName: import-service-files

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-2
  environment:
    UPLOAD_FOLDER: uploaded
    BUCKET: ${self:custom.bucketName}
    REGION: ${self:provider.region}
  httpApi:
    cors: true
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:ListBucket'
        - 's3:GetObject'
        - 's3:PutObject'
      Resource:
        - 'arn:aws:s3:::${self:custom.bucketName}'
        - 'arn:aws:s3:::${self:custom.bucketName}/*'

functions:
  importProductsFile:
    handler: handler.importProductsFile
    description: |
      This function requires a query string parameter "name" specifying the filename.
      Example usage: /import?name=myFile.csv
    events:
      - httpApi:
          path: /import
          method: get
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: ${self:custom.bucketName}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
            - suffix: .csv
