service: import-service

frameworkVersion: "3"

custom:
  accountId: 449436809015
  bucketName: import-service-files

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-2
  environment:
    UPLOAD_FOLDER: uploaded
    BUCKET: ${self:custom.bucketName}
    AWS_REGION: ${self:provider.region}
  httpApi:
    cors: true
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:ListBucket'
        - 's3:GetObject'
        - 's3:PutObject'
      Resource:
        - 'arn:aws:s3:::${self:custom.bucketName}'
        - 'arn:aws:s3:::${self:custom.bucketName}/*'

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - httpApi:
          path: /import
          method: get
          request:
            parameters:
              querystrings:
                name: true
